from open_ephys.analysis import Session
import numpy as np
import sys
import pandas as pd
import matplotlib.pyplot as plt
from tabulate import tabulate

# holds the 4 sec recording generated by running 'python test_record.py --fetch' (change the path below as needed)
directory = 'C:\\Users\\Pavel\\OneDrive\\Documents\\Open Ephys\\2022-04-06_16-19-10'

# create a session object
session = Session(directory)

# get the first (and only in this case) record node
node = session.recordnodes[0]

# get the first (and only in this case) recording
recording = node.recordings[0]

# show continuous data 
num_streams = len(recording.continuous)
subplot_idx = 1
fig = plt.figure(1)

for stream in recording.continuous:

    # get stream name
    name = stream.name

    # get number of channels and number of samples per channel
    num_samples, num_channels = np.shape(stream.samples)

    # get all samples from this stream
    all_channels = stream.samples

    # get samples from only the first channel 
    first_channel = all_channels[:,0]

    # get the timestamps (in sample number since start of recording)
    timestamps = stream.timestamps

    # get the timestamps (in synchronzied seconds since start of recording) 
    synchronized = stream.synchronized 

    # configure plot
    ax = fig.add_subplot(num_streams, 1, subplot_idx)
    ax.set_title(name)
    ax.set_ylabel('Voltage')

    # show the data
    ax.plot(timestamps, first_channel)

    print('{} has {} channels'.format(stream.name, num_channels))

    subplot_idx += 1

ax.set_xlabel('Sample Number')
plt.show()

# show event data
#print(tabulate(recording.events, headers='keys', tablefmt='psql'))

#TODO show spike data